# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - listenadmin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:  
    environment: Azure
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # ✅ 添加这行
      contents: read           # 这行你已有，保留
    env:                             # 这里注入环境变量，供 build 时使用
      AZURE_SQLSERVER: ${{ secrets.AZURE_SQLSERVER }}
      AZURE_REDIS_CONNECTION: ${{ secrets.AZURE_REDIS_CONNECTION }}
      JWT_KEY: ${{ secrets.AZURE_JWT_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Listening.Admin.Api/Listening.Admin.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Listening.Admin.Api/Listening.Admin.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66177CAD43564FE0944BD99952F12694 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_302DD1DDED9B455487B899CDB6F929F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5FF55F724E5481DB3878AC734381CD3 }}

      - name: Configure App Settings via Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group apifortest_group \
              --name listenadmin \
              --settings \
                RedisConnection="${{ secrets.AZURE_REDIS_CONNECTION }}" \
                ConnectionStrings__SqlServer="${{ secrets.AZURE_SQLSERVER }}" \
                JWT__SecKey="${{ secrets.AZURE_JWT_KEY }}" \
                JWT__ExpiresMinutes="60" \
                JWT__RefreshTokenExpiresHours="189" \
                JWT__Issuer="test" \
                JWT__Audience="test"
  deploy:  
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66177CAD43564FE0944BD99952F12694 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_302DD1DDED9B455487B899CDB6F929F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5FF55F724E5481DB3878AC734381CD3 }}
          enable-AzPSSession: false


      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'listenadmin'
          slot-name: 'Production'
          package: .
          
